// Exportação de todos os componentes para facilitar a importação.
export * from "./button8"
export * from "./checkBox8"
export * from "./date8"
export * from "./dateInterval8"
export * from "./file8"
export * from "./image8"
export * from "./select8"
export * from "./input8"
export * from "./multiSelect8"
export * from "./sound8"
export * from "./table8"
export * from "./text8"
export * from "./textArea8"
export * from "./video8"